services:
    dmzx.notifyuponreply.listener:
        class: dmzx\notifyuponreply\event\listener
        arguments:
            - '@user'
            - '@request'
            - '@template'
            - '@auth'
        tags:
            - { name: event.listener }            